### ISSUE TITLE
Mojang copyright in the main menu is displayed incorrectly after installing Better Modlist

### ISSUE THREAD

**Issue by Tapacywka** [1foxy2/neo_mod_menu#1]
After installing Better Modlist, the text in the bottom right corner (Mojang copyright) has shifted from its original position, overlapping with other text (which I added with the Main Menu Credits mod). Without Better Modlist this problem is not observed.
![image](https://github.com/user-attachments/assets/28085bb0-d461-480a-b190-3fa3523bf2ec)

**Comment by 1foxy2** [comment]
should be fix, atleast with mods a tested with
