### ISSUE TITLE
[BUG] Using mouse back button to return to game causes crash

### ISSUE THREAD

**Issue by ryanfp** [1foxy2/neo_mod_menu#11]
### **Describe the bug**

Whenever I'm in the pause screen changing settings or mods and I use the mouse back button to close the menu and return to the game it crashes. Confirmed it's this mod, I switched out catalogue and this one and tested multiple times. I'm not sure which mod adds the capability to navigate menus using the mouse back button, I think Quark? 

### **To Reproduce**

1. Pause the game
2. Navigate any menu or change any setting you want (Optional)
3. Use mouse back button to exit the menu and return to the game
4. Game crashes

### **Expected behavior**

I expected to be able to close the menu

### **Forge version**

47.2.0

### **Better modlist version**

0.1.5

### **Additional context**

MC Logs [link](https://mclo.gs/mQ6Ocyv)

Worth noting I'm using Sinytra Connector and a slew of other mods. Thanks!

**Comment by 1foxy2** [comment]
i will look at it tomorrow. it would be helpful if you find the exact mods it happens with (doesn't happen with just quark and better modlist for me)

**Comment by ryanfp** [comment]
Cool no worries. I'll try to see, maybe an issue with connector and other mods? I'm sure there's one that calls the fabric mod ModList, who knows.

**Comment by 1foxy2** [comment]
sorry but i can't reproduce the crash, can you send your modpack?

**Comment by ryanfp** [comment]
I've been trying to replicate it in other duplicate instances (I use Prism) and I have not been able to reproduce it either. I removed all texture/resource packs from the one instance where it was still happening and it stopped as well, so it must have been issues with a texture or menu change. 

I can still send the modlist but I think it was just a bad download on my part

Thank you for your help tho! Feel bad for wasting your time haha
