### ISSUE TITLE
[BUG] `UnsupportedOperationException: Path not associated with default file system.` 

### ISSUE THREAD

**Issue by SettingDust** [1foxy2/neo_mod_menu#15]
Error on my nested jar

![图片](https://github.com/user-attachments/assets/32c7ccd9-ca2c-4d53-baba-f5b16086bf4f)

Will the https://github.com/Sinytra/Connector/blob/1.20.1/src/main/java/org/sinytra/connector/loader/ConnectorEarlyLoader.java#L35-L37 work?

**Comment by 1foxy2** [comment]
it does, just forgot to backport.
