### ISSUE TITLE
Some mod icons doesn't work.

### ISSUE THREAD

**Issue by digi2303** [1foxy2/neo_mod_menu#2]
I'm using Forgified Core modpack.
![Ekran görüntüsü 2024-08-24 192324](https://github.com/user-attachments/assets/6d280cd6-72f4-4f62-bc39-d446b3097a00)
![Ekran görüntüsü 2024-08-24 192339](https://github.com/user-attachments/assets/621e1aef-388a-4b1f-b328-15d504202fbf)

**Comment by 1foxy2** [comment]
right now there is two reasons for this to happen, either mod don't have an icon (like customSkinLoader) or it isnt a square (like immersice ui).  i can't do anything about first reason but for second one i can do something like this 
![image](https://github.com/user-attachments/assets/a12d8628-acf8-4da8-8e82-f85814759aa1)

**Comment by digi2303** [comment]
Can you please do the second?

**Comment by 1foxy2** [comment]
done

**Comment by BookerCatch** [comment]
As a nice quality of life tweak and general improvement suggestion, could you possibly implement what's being done here with Mod Menu Stylizer?

https://modrinth.com/mod/modmenustylizer

I tried using this mod in conjunction, but it won't work.

**Comment by 1foxy2** [comment]
yeah, sure. something like that was in my todo list, didn't know there was a mod for this.

**Comment by test-tempacc** [comment]
> sure. something like that was in my todo list, didn't know there was a mod for this.

Any update on this? Thanks!

**Comment by 1foxy2** [comment]
[replace icon](https://github.com/1foxy2/neo_mod_menu/wiki/Replace-mods-icon), [adding a badge to mod](https://github.com/1foxy2/neo_mod_menu/wiki/adding-badges-to-mods), [adding a new badge](https://github.com/1foxy2/neo_mod_menu/wiki/Custom-Badges)

**Comment by test-tempacc** [comment]
> [replace icon](https://github.com/1foxy2/neo_mod_menu/wiki/Replace-mods-icon), [adding a badge to mod](https://github.com/1foxy2/neo_mod_menu/wiki/adding-badges-to-mods), [adding a new badge](https://github.com/1foxy2/neo_mod_menu/wiki/Custom-Badges)

Oh, sorry- I didn't realise there was a wiki. Thanks again!
