### ISSUE TITLE
[BUG] ibe editor config opens with entering mod list menu

### ISSUE THREAD

**Issue by xg787** [1foxy2/neo_mod_menu#5]
**Describe the bug**
ibe editor config opens with entering mod list menu

**To Reproduce**
1. load ibe editor with mod menu
2. Click on mods
3. See error

**Expected behavior**
mod list

**Screenshots**
https://github.com/user-attachments/assets/8cd0e468-4a9b-4676-9916-0e0c11e8db83

**Comment by 1foxy2** [comment]
fixed in 0.0.3, thx for finding the bug
