### ISSUE TITLE
[BUG] The `library_list` line doesn't work

### ISSUE THREAD

**Issue by Tapacywka** [1foxy2/neo_mod_menu#6]
**Describe the bug**
The `library_list` line doesn't work, even if you specify certain mods there, the badge and the condition of hiding libraries does not apply to them.

**To Reproduce**
1. Go to 'config/mod_menu-client.toml';
2. Add mods to 'library_list';
3. Save the file;
4. Open the game, go to the mods list and check it.

**Expected behavior**
The badges should be applied to the mods specified in the config, and the mods themselves should be hidden from the list because `show_libraries = false` is enabled.

**NeoForge version**
21.1.37 (1.21.1)

**Better Mod List version**
1.0.6 (1.21.1)

**Screenshots**
![image](https://github.com/user-attachments/assets/1dfedaa3-2e89-4c42-85b2-33c31560abf8)
![image](https://github.com/user-attachments/assets/fd18175f-7316-4ad7-aa02-65aa72d89214)
![image](https://github.com/user-attachments/assets/656cb7bb-a1d8-4397-abda-adb20653e81b)
![image](https://github.com/user-attachments/assets/06340016-18be-40d1-ad3b-2df44f607f33)
![image](https://github.com/user-attachments/assets/5ab22b0b-4306-4d22-9541-e8490d788c96)
![image](https://github.com/user-attachments/assets/dd0d73e3-626e-493c-b427-33257021f0d8)

**Additional context**
You can check it using my [modpack](https://modrinth.com/modpack/forgified-core/version/v21.1.4), it's already preconfigured so you don't have to do anything yourself, just run it.

**Comment by 1foxy2** [comment]
![image](https://github.com/user-attachments/assets/b23b70a3-5170-4725-b0d1-963b5bb0b719)
fixed
