### ISSUE TITLE
Incompatible with the "Monocle" mod

### ISSUE THREAD

**Issue by MrWindDog** [1foxy2/neo_mod_menu#7]
From testing, I've found out that the "Monocle" mod (from the TauMC beta server) (https://discord.com/channels/1140803582208245810/1270040212742996008/1272672959286476852) and found out that when using both of the Monocle and Better Modlists mod results in the game crashing. If you would like me to send any logs or the such I will be glad to do so.

**Comment by 1foxy2** [comment]
![image](https://github.com/user-attachments/assets/e3fdbf4e-8254-4b61-a5db-894089d9986a)
works fine for me, can you send latest.log?

**Comment by MrWindDog** [comment]
Sure, here is the log:
[latest.log](https://github.com/user-attachments/files/17166075/latest.log)

And here is the rash report if you need it:
[crash-2024-09-27_08.00.34-fml.txt](https://github.com/user-attachments/files/17166080/crash-2024-09-27_08.00.34-fml.txt)

**Comment by MrWindDog** [comment]
It could possibly be a problem on my end because I’m using macOS and not windows

**Comment by 1foxy2** [comment]
are you sure this is caused by my mod? i got crash with just connector, connectorextras, ffapi, embeddium, iris, monocle. also try using official sodium and iris

**Comment by MrWindDog** [comment]
Yes, you are partially correct (just found out due to a oversight of mine), but it is a problem from an error given by the mod (as shown in the screenshot) when both connector _and_ monocle being enabled with the better modlist mod installed
<img width="1710" alt="Screenshot 2024-09-27 at 10 13 53 AM" src="https://github.com/user-attachments/assets/7777ac8c-a36a-4f62-ae3c-dd4e820ec771">

**Comment by 1foxy2** [comment]
i can fix that but whats the point if its gonna crash anyways after that?

**Comment by MrWindDog** [comment]
The mods work together without the better modlist installed. It is only then when the modlist is installed that it crashes

**Comment by 1foxy2** [comment]
oh, you're right. they do in neoforge 21.1.61 but doesn't in 21.1.62, weird

**Comment by MrWindDog** [comment]
Oh. I didn't even think of checking the neoforge version. I am sorry about that

**Comment by 1foxy2** [comment]
fixed

**Comment by MrWindDog** [comment]
Thank you! I'm sorry for any confusion I may have caused throughout all of this
