### ISSUE TITLE
Buttons Merge on Game/Pause Menu | Better Modlist [(Neo)Forge] 1.20.1 ver 0.1.2 | Forge ver 47.1.3

### ISSUE THREAD

**Issue by YisusClaus** [1foxy2/neo_mod_menu#8]
**Describe the bug**
Buttons Merge on Game/Pause Menu

**To Reproduce**
- Install minecraft 1.20.1 and forge 47.1.3 on Curseforge.
- Drop Better_Modlist-0.1.2.jar (1.20.1) on mods folder.

**Expected behavior**
To show the "Options", "Open to LAN" and "Save & Quit" Buttons Normally.

**Forge version**
47.1.3 (recommended for Sinytra Connector) (Sinytra Connector not included on this example but the outcome is the same)

**Better modlist version**
1.20.1 | 0.1.2

**Screenshots**

Game Menu:
![Merged_Buttons](https://github.com/user-attachments/assets/1321795d-f007-44ba-95d4-948ae4bd5320)

Mods Folder:
![mods_folder](https://github.com/user-attachments/assets/43bcb708-c4dd-47dd-9fad-af1aac3406cb)

Modlist (Forge Config Screens doesn't affect outcome):
![Modlist](https://github.com/user-attachments/assets/fa728433-627d-4a57-b24b-b5b17b4eeb94)

**Additional context**
Tested on my modpack that contains 71 or so mods + on a clean install and the merge happens either way.

**Comment by 1foxy2** [comment]
fixed. there wasn't mods button in gamemenu on old forge versions so it breaks
