### ISSUE TITLE
[BUG] Crash on 1.20.1

### ISSUE THREAD

**Issue by SettingDust** [1foxy2/neo_mod_menu#9]
**Describe the bug**
https://github.com/1foxy2/neo_mod_menu/blob/forge-1.20.1/src/main/java/com/terraformersmc/mod_menu/mixin/MixinBrandingControl.java#L41

`ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1`

The fix in https://github.com/1foxy2/neo_mod_menu/blob/master/src/main/java/com/terraformersmc/mod_menu/mixin/MixinBrandingControl.java#L41 need to backport

BTW. monocle is a mod that has some logic running on SERVICE/PLUGIN layer. Forge isn't allowing a jar running on PLUGIN and GAME at the same time. It has to add a mod locator and load the mod jar into Forge.

**To Reproduce**
Not sure

**forge version**
47.3.11
**better modlist version**
0.1.3

**Comment by 1foxy2** [comment]
fixed. thx for explaining monocle
